title: Meh
author: It's me :(
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  how boring it all is :(
# social links
twitter_username: iHaqi_
github_username:  ihaqi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
